server:
  port: 8080

spring:
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
ignored:
  prefix: SYS,ERP,CRM,CC

combo:
  base-entity: com.funny.combo.core.base.BaseEntity
  base-dao: com.funny.combo.core.base.BaseMapper
  encrypt:
    handler: com.funny.combo.encrypt.handler.CryptTypeHandler
    columns: _encryped,_encry,_encrypt
  hash:
    handler: com.funny.combo.encrypt.handler.HashTypeHandler
    columns: _hash
  sql:
    insert: insertSelective
    update: updateSelectiveById
    find: findEntityById
    findList: listByCondition
    count: count
    delete: deleteById
  entity:
    id: id
    create-time: gmt_created
    modify-time: gmt_modified
    is-del: is_del